### ISSUE TITLE
the opensmalltalk.org web site no longer works

### ISSUE THREAD

**Issue by alanz** [OpenSmalltalk/opensmalltalk.github.io#1]
It goes to a github "site not found" page

**Comment by krono** [comment]
Thanks.
We're working on it.

**Comment by fniephaus** [comment]
The settings page reveals thee problem:

> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/.

**Comment by krono** [comment]
As I said, we're on it

**Comment by robohack** [comment]
Still not working?

**Comment by krono** [comment]
Sorry, lost track :(

**Comment by krono** [comment]
should be fixed, finally :)
